# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedb',
            name='season',
            field=models.CharField(choices=[('Winter', '冬'), ('Spring', '春'), ('Summer', '夏'), ('Fall', '秋'), ('Unknow', '未定義')], max_length=500, verbose_name='シーズン'),
        ),
    ]
