# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_animedb_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedb',
            name='weekday',
            field=models.CharField(choices=[('0', '月'), ('1', '火'), ('2', '水'), ('3', '木'), ('4', '金'), ('5', '土'), ('6', '日')], default=1, max_length=500, verbose_name='曜日'),
        ),
        migrations.AlterField(
            model_name='animedb',
            name='year',
            field=models.CharField(choices=[('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013')], max_length=500, verbose_name='放送年'),
        ),
    ]
