# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170218_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedb',
            name='weekday',
            field=models.CharField(choices=[('0', '月'), ('1', '火'), ('2', '水'), ('3', '木'), ('4', '金'), ('5', '土'), ('6', '日')], default=0, max_length=500, verbose_name='曜日'),
        ),
    ]
