# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170218_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedb',
            name='status',
            field=models.CharField(default='Completed', max_length=500, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='animedb',
            name='weekday',
            field=models.CharField(choices=[('--', '--'), ('Mon', '月'), ('Tue', '火'), ('Wed', '水'), ('Thu', '木'), ('Fri', '金'), ('Sat', '土'), ('Sun', '日')], default=0, max_length=500, verbose_name='曜日'),
        ),
    ]
